name: CI

# Déclenchement sur push et PR vers main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer .NET 9
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # 3. Restore des dépendances
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build en Release
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # 5. Exécuter les tests
      - name: Run tests
        run: dotnet test --no-restore --configuration Release `
             /p:CollectCoverage=true `
             /p:CoverletOutputFormat=lcov `
             /p:CoverletOutput=TestResults/ `
             --verbosity normal

      # 6. Publier les résultats de couverture
      - name: Publish coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: TestResults/coverage.info